### ISSUE TITLE
setup.py is missing

### ISSUE THREAD

**Issue by exenGT** [joselado/pygra#3]
Hi,

I found that there is no setup.py in the package repository, so I can't install it using pip. Could you kindly fix it? Thanks!

Best regards,
Jingyang

**Comment by exenGT** [comment]
Also, it seems that the __init__.py is empty, so python cannot recognize the module.

**Comment by joselado** [comment]
Dear exenGT,

thank you for your message. Currently the package cannot be installed with pip, so it has to be installed manually. To install it you just need to clone the repository and add the "src/pygra" directory to your Python path.

Best regards,
Jose
