### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by hungpham2017** [joselado/pygra#5]
Hello,

Thank you for the excellent library. It is very helpful for my research.
I wonder how pygra is supposed to be cited. Is there any publication or relating work for pygra?

Thank you,
Hung

**Comment by joselado** [comment]
Dear Hung,

thank you for your message and for your nice feedback!

You do not have to cite any publication in relation to pygra. If you would like to put a reference for others to know how some calculation was done, you could just refer to the web address of the pygra library "https://github.com/joselado/pygra"

Best regards,
Jose

**Comment by hungpham2017** [comment]
Sounds good to me. Thanks again.
Hung
